[[repo]]
name = "komodo-app-stacks"
tags = ["sync"]
[repo.config]
git_account = "simtel12"
repo = "simtel12/komodo-app-stacks"

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system", "sync"]
config.schedule = "Every day at 01:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = false }
]

##

[[procedure]]
name = "Deploy if changed"
tags = ["sync"]

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "RunSync", execution.params.sync = "komodo-app-stacks", enabled = true }
]

[[procedure.config.stage]]
name = "Stage 2"
enabled = true
executions = [
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = "*", enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system", "sync"]
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params = {}, enabled = true }
]

##

[[resource_sync]]
name = "komodo-app-stacks"
tags = ["sync"]
[resource_sync.config]
repo = "simtel12/komodo-app-stacks"
git_account = "simtel12"
webhook_enabled = false
resource_path = ["services", "common-vars.toml"]
include_variables = true

##

[[resource_sync]]
name = "komodo-op-sync"
tags = [
  "infrastructure",
  "1password-connect",
  "sync"
]
[resource_sync.config]
repo = "simtel12/deploy-komodo-op"
git_account = "simtel12"
resource_path = ["stack.toml"]